title:  Sylvia  Cims
description: Fachinformatikerin Anwendungsentwicklung
site_title: Mehrapi

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Mehrapi
blog_url: https://sieblogt.github.io
email: sylviiaa@protonmail.com
# keybase_username: abhn
twitter_username: mehrapi


# absolute or relative
profile_picture: assets/images/SC.jpg

# Google Analytics ID
google_analytics: UA-179020521-1

gallery: assets/album/

# plugins



  

